name: Reformat Code in PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  format-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install pre-commit

      - name: Run pre-commit hooks
        run: |
          source venv/bin/activate
          pre-commit install
          pre-commit run --all-files || true

      - name: Configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.changes_detected == 'true'
        run: |
          git add --all
          git commit -m "[auto] Pre-commit run on all files"
          git push
