name: "Ensure Active Weka Mount"
description: "Make sure weka mount is active"

runs:
  using: "composite"
  steps:
    - name: Ensure active weka mount
      shell: bash
      run: |
        timeout --preserve-status 300 ./.github/scripts/cloud_utils/mount_weka.sh
