name: 'Setup Python Environment'
description: 'Sets up Python and installs dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Telemetry
      uses: catchpoint/workflow-telemetry-action@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
        cache-dependency-path: |
          requirements-dev.txt
          setup.py

    - name: Install Dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip                    
        python3 -m pip install -r requirements-dev.txt
        python3 -m pip install pytest-github-report
