repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.1
  hooks:
    - id: black
      language_version: python3
      args: ["--line-length=120"]
- repo: https://github.com/cpp-linter/cpp-linter-hooks
  rev: v0.6.0
  hooks:
    - id: clang-format
      args: [--style=file, --version=16]
