# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
import os
from setuptools import setup, find_packages


def read_readme():
    with open("README.md", encoding="utf-8") as f:
        return f.read()


def version_scheme(version):
    with open("VERSION", "r") as f:
        return f.read().strip()


setup(
    name="torch-ttnn",
    description="PyTorch 2.0 TTNN Compiler",
    long_description=read_readme(),
    long_description_content_type="text/markdown",
    url="https://github.com/tenstorrent/pytorch2.0_ttnn",
    author="Tenstorrent",
    author_email="info@tenstorrent.com",
    license="Apache-2.0",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    version=version_scheme(""),
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "numpy>=1.24.0",
        "tqdm>=4.65.0",
        "matplotlib>=3.7.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.2.0",
        "scipy>=1.10.0",
        "pillow>=9.5.0",
        "requests>=2.28.0",
        "tensorboard>=2.12.0",
        "transformers>=4.30.0",
        "datasets>=2.12.0",
        "evaluate>=0.4.0",
        "accelerate>=0.20.0",
        "sentencepiece>=0.1.99",
        "protobuf>=3.20.0",
        "safetensors>=0.3.1",
        "huggingface-hub>=0.15.1",
        "tokenizers>=0.13.3",
        "regex>=2023.6.3",
        "filelock>=3.12.2",
        "packaging>=23.1",
        "typing_extensions>=4.7.1",
        "psutil>=5.9.5",
        "pyyaml>=6.0",
        "timm>=0.9.2",
        "einops>=0.6.1",
        "opencv-python>=4.7.0",
        "pycocotools>=2.0.6",
        "albumentations>=1.3.1",
        "kornia>=0.7.0",
        "torchmetrics>=1.2.0",
        "pytorch-lightning>=2.0.0",
        "wandb>=0.15.0",
        "tensorboardX>=2.6",
        "thop>=0.1.1",
        "fvcore>=0.1.5",
        "iopath>=0.1.9",
        "pytorchvideo>=0.1.5",
        "av>=10.0.0",
        "decord>=0.6.0",
        "moviepy>=1.0.3",
        "pytorch3d>=0.7.4",
        "trimesh>=3.22.0",
        "open3d>=0.17.0",
        "pytorch-geometric>=2.3.0",
        "networkx>=3.1",
        "rdkit>=2023.3.1",
        "biopython>=1.81",
        "scikit-image>=0.20.0",
        "imageio>=2.31.0",
        "imageio-ffmpeg>=0.4.8",
        "pydantic>=2.0.0",
        "fastapi>=0.100.0",
        "uvicorn>=0.23.0",
        "python-multipart>=0.0.6",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "bcrypt>=4.0.1",
        "python-dotenv>=1.0.0",
        "sqlalchemy>=2.0.0",
        "alembic>=1.11.0",
        "pytest>=7.4.0",
        "pytest-cov>=4.1.0",
        "pytest-xdist>=3.3.1",
        "pytest-timeout>=2.1.0",
        "pytest-mock>=3.11.1",
        "pytest-env>=1.0.1",
        "pytest-benchmark>=4.0.0",
        "pytest-profiling>=1.7.0",
        "pytest-sugar>=0.9.7",
        "pytest-html>=4.1.1",
        "pytest-metadata>=3.0.0",
        "pytest-randomly>=3.12.0",
        "pytest-repeat>=0.9.1",
        "pytest-rerunfailures>=12.0",
        "pytest-selenium>=4.0.0",
        "pytest-variables>=3.0.0",
        "pytest-xprocess>=0.23.0",
        "pytest-instafail>=0.5.0",
        "pytest-clarity>=1.0.1",
        "pytest-emoji>=2.2.0",
        "pytest-json-report>=1.5.0",
        "pytest-html-reporter>=0.2.9",
        "pytest-reportlog>=0.3.0",
        "pytest-reportportal>=5.3.0",
    ],
    extras_require={
        "ttnn": [
            "ttnn>=0.1.0; platform_system=='Linux' and python_version=='3.10'",
        ],
        "dev": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "black>=23.7.0",
            "isort>=5.12.0",
            "flake8>=6.1.0",
            "mypy>=1.5.0",
            "pre-commit>=3.3.3",
            "sphinx>=7.1.2",
            "sphinx-rtd-theme>=1.3.0",
            "sphinx-autodoc-typehints>=1.23.0",
            "sphinx-copybutton>=0.5.2",
            "sphinx-tabs>=3.4.1",
            "sphinx-panels>=0.6.0",
            "sphinx-autobuild>=2021.3.14",
            "sphinx-autodoc-typehints>=1.23.0",
            "sphinx-copybutton>=0.5.2",
            "sphinx-tabs>=3.4.1",
            "sphinx-panels>=0.6.0",
            "sphinx-autobuild>=2021.3.14",
        ],
    },
)
