name: 'Run Multi-device Model tests'
description: 'Run Model tests with mesh devices'
inputs:
    commit_report:
      description: 'Commit report input (None, Docs, All)'
      required: false
      default: 'None'
runs:
  using: "composite"
  steps:
    - name: Run Multi Device Tests
      shell: bash
      run: |
        set +e
        if [ "${{ github.event.inputs.commit_report }}" == "None" ]; then
          num_iterations=1
        else
          num_iterations=5
        fi
        python3 -m pytest --github-report tests/multi_device/ --data_parallel --report_nth_iteration=$num_iterations --gen_op_accuracy_tests -s
        exit_code=$?  # Capture the exit code
        if [ $exit_code -eq 5 ]; then
          echo "Error: pytest returned exit code 5 (No tests to run) in the first test group.";
          exit 1;  # Fail the workflow
        elif [ $exit_code -ne 0 ]; then
          echo "Failure: Tests failed with exit code $exit_code.";
          exit 1;  # Fail the workflow for other errors
        fi
        echo "Success: Tests passed!";
        ls -l
        cd metrics
        ls -l
        cd ..
        exit 0;
