name: 'Setup Python Environment from wheel'
description: 'Sets up Python and installs dependencies from wheel'
inputs:
  enable-telemetry:
    description: 'Whether to enable telemetry (will fail if enabled but permissions are missing)'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    # TODO: Identify which workflows/jobs should have telemetry explicitly enabled (enable-telemetry: 'true')
    # DISABLED: Telemetry is currently disabled due to permissions issues on self-hosted runners
    # (Error: Access to the path '/home/ubuntu/actions-runner/_work/_actions/catchpoint' is denied).
    # Once we identify which jobs need telemetry, we can enable it explicitly and fix permissions.
    # - name: Setup Telemetry
    #   if: ${{ inputs.enable-telemetry == 'true' }}
    #   uses: catchpoint/workflow-telemetry-action@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - uses: actions/download-artifact@v4
      with:
        name: torch_ttnn-distributions
        path: dist/

    - name: Install Dependencies from wheel
      shell: bash
      run: |
        ls -al dist/
        df -h
        python3 -m pip install --upgrade pip
        # Install wheel with dev dependencies
        python3 -m pip install "dist/torch_ttnn-*.whl[dev]"
        # Install test dependencies
        python3 -m pip install pytest-github-report
        # ensure package used from wheel installation
        rm -rf torch_ttnn
        df -h

    - uses: ./.github/actions/common_cleanup
