name: 'Cleanup Model Cache'
description: 'Removes Huggingface and TorchVision model cache and reports free disk space'
runs:
  using: "composite"
  steps:
    - name: Cleanup model cache
      shell: bash
      run: |
        df -h
        python3 -m pip cache purge
        python3 tools/huggingface_delete_cache.py
        rm -rf ~/.torch/models
        free -h
        df -h
