name: "Community Issue / PR Labeling Workflow"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  call-central-workflow:
    permissions:
      issues: write
      pull-requests: write
    uses: tenstorrent/tt-github-actions/.github/workflows/on-community-issue.yml@main

