name: Run pre-commit All

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  format-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate          
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "[auto] Pre-commit run on all files" || echo "No changes to commit"
          git push || echo "No changes to push"
